unitaryfund/metriq-client

metriq/models/method.py

Updated the file by adding data types that corresponded with Postman. Also added descriptions for the new types in the comment.

Upated Method Model

---

metriq/models/result.py

Updated Result Model using the results.js model in the QxQ milestone

Updated Result Model

---

metriq/models/submission.py

Not many changes needed. One additional type added.

Update Submission Model

---

metriq/models/tag.py

Updated tag model, added one new type.

Update Tag Model

---

metriq/models/user.py

Created a new file for the user model. Added multiple types taken from the .js file.

User-model

---

metriq/models/__init__.py
metriq/models/moderationReport.py

Added Moderation report file and updated the init file to be able to read the Moderation report classes

Moderation report model

---

examples/method_delete.py
examples/submission_get.py
examples/task_delete.py
metriq/client.py
metriq/models/submission.py

Remove method delete

---

examples/submission_get.py
examples/task_delete.py
metriq/client.py
metriq/models/submission.py

Remove delete task

---

metriq/client.py

Debugging method GET route with ['data'] key given to method constructor.

Method GET Route debug

---

examples/submission_get.py
metriq/client.py
metriq/models/submission.py

Updated the models in submissions.py

Submission GET route

---

metriq/models/platform.py

Created the platform model. Renamed "platform" to "environment". Used task.py as a reference.

Create Platform Model

---

examples/platform_get.py
metriq/client.py

Created GET platform file. Added `@handler`  for platform_get to client.py

Created GET Platform

---

examples/platform_add.py
metriq/client.py

Created POST route for platform. Added `@handler` for platform_add

Create POST platform

---

examples/platform_update.py
metriq/client.py

Created a file for platform update. Added an `@handler` to client.py for platform_update

Created platform_update.py

---

examples/submission_add_method.py
examples/submission_add_tag.py
examples/submission_add_task.py

[UnitaryHack] Add examples for /submission_add_method, /submission_add_task, /submission_add_tag

---

examples/result_get.py
examples/result_metric_names.py

Added examples for results API except for results_add.py because it was already there.
Open for any improvements suggestions.
Closes #73

Added examples for results API endpoints

---

examples/platform_get_names.py
metriq/client.py

Please let me know if it needs to be updated!

Platform issue 88

---

metriq/client.py

fixing indentation bug.

---

examples/task_get_network.py
metriq/client.py

This one I am a little bit more unsure about. Because the API endpoint shows "readNetworkGraph" so  should the results be numerical or should they be visual ie a graph?

Route network issue 85

---

metriq/models/moderation_report.py

Re-add missing model `moderation_report`
Fixes #106

Add renamed model

---

metriq/client.py

Closes #110 
Fixing the endpoint issues as pointed out by @karlaspuldaro in #110. 
Thank you again, @karlaspuldaro!

Fixing the method, platform, and result metric name end points.

---

metriq/models/submission.py

Adding codeUrl to submission create and update requests.

---

metriq/models/result.py

Adding standard error and sample size.

---

examples/result_add.py

Add submission_id in result_add example

---

metriq_client/client.py
metriq_client/models/moderation_report.py
metriq_client/models/platform.py
metriq_client/models/result.py
metriq_client/models/submission.py
metriq_client/models/task.py

Removing deprecated fields attribute from Pydantic.
